#!/usr/bin/env python

import cgi;
import os
import urllib

BASE_PATH = "/local/QED/data"

print "Content-Type: application/json\n"

form = cgi.FieldStorage()
filepath = urllib.unquote(form.getvalue("filepath"))

dirs=[]
files=[]
for f in os.listdir(BASE_PATH + filepath):
    if not f.startswith("."):
        label = os.path.basename(f)
        item = '{"label":"%s", "uri":"%s"}' % (label, os.path.join(filepath,f))

        if os.path.isdir(BASE_PATH + filepath + f):
            dirs.append(item)
        else:
            files.append(item)

print '{ "directories": [' + ",".join(dirs) + '], "files": [' + ",".join(files) + '] }'
